//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaSpace.Grammar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinguaSpace.Grammar.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string COL_ACTIVE {
            get {
                return ResourceManager.GetString("COL_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string COL_COMMENT {
            get {
                return ResourceManager.GetString("COL_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExampleId.
        /// </summary>
        internal static string COL_EXAMPLE_ID {
            get {
                return ResourceManager.GetString("COL_EXAMPLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string COL_EXCEPTION {
            get {
                return ResourceManager.GetString("COL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        internal static string COL_EXPANDED {
            get {
                return ResourceManager.GetString("COL_EXPANDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrammarId.
        /// </summary>
        internal static string COL_GRAMMAR_ID {
            get {
                return ResourceManager.GetString("COL_GRAMMAR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NativeLang.
        /// </summary>
        internal static string COL_NATIVE_LANG {
            get {
                return ResourceManager.GetString("COL_NATIVE_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NativeText.
        /// </summary>
        internal static string COL_NATIVE_TEXT {
            get {
                return ResourceManager.GetString("COL_NATIVE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentTopicId.
        /// </summary>
        internal static string COL_PARENT_TOPIC_ID {
            get {
                return ResourceManager.GetString("COL_PARENT_TOPIC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string COL_POSITION {
            get {
                return ResourceManager.GetString("COL_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleId.
        /// </summary>
        internal static string COL_RULE_ID {
            get {
                return ResourceManager.GetString("COL_RULE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowRule.
        /// </summary>
        internal static string COL_SHOWRULE {
            get {
                return ResourceManager.GetString("COL_SHOWRULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string COL_SHUFFLE {
            get {
                return ResourceManager.GetString("COL_SHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetLang.
        /// </summary>
        internal static string COL_TARGET_LANG {
            get {
                return ResourceManager.GetString("COL_TARGET_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetText.
        /// </summary>
        internal static string COL_TARGET_TEXT {
            get {
                return ResourceManager.GetString("COL_TARGET_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string COL_TITLE {
            get {
                return ResourceManager.GetString("COL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicId.
        /// </summary>
        internal static string COL_TOPIC_ID {
            get {
                return ResourceManager.GetString("COL_TOPIC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.
        /// </summary>
        internal static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Examples WHERE ExampleId = @ExampleId.
        /// </summary>
        internal static string DELETE_EXAMPLES {
            get {
                return ResourceManager.GetString("DELETE_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Rules WHERE RuleId = @RuleId.
        /// </summary>
        internal static string DELETE_RULES {
            get {
                return ResourceManager.GetString("DELETE_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Topics WHERE TopicId = @TopicId.
        /// </summary>
        internal static string DELETE_TOPICS {
            get {
                return ResourceManager.GetString("DELETE_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkExamplesRules.
        /// </summary>
        internal static string FK_EXAMPLES_RULES {
            get {
                return ResourceManager.GetString("FK_EXAMPLES_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkRulesTopcs.
        /// </summary>
        internal static string FK_RULES_TOPICS {
            get {
                return ResourceManager.GetString("FK_RULES_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkTopicsTopics.
        /// </summary>
        internal static string FK_TOPICS_TOPICS {
            get {
                return ResourceManager.GetString("FK_TOPICS_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Examples (ExampleId, RuleId, Position, TargetText, NativeText, Active, Exception)
        ///VALUES (@ExampleId, @RuleId, @Position, @TargetText, @NativeText, @Active, @Exception).
        /// </summary>
        internal static string INSERT_EXAMPLES {
            get {
                return ResourceManager.GetString("INSERT_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Grammar (GrammarId, Title, Comment, TargetLang, NativeLang, Shuffle, ShowRule) 
        ///VALUES (@GrammarId, @Title, @Comment, @TargetLang, @NativeLang, @Shuffle, @ShowRule).
        /// </summary>
        internal static string INSERT_GRAMMAR {
            get {
                return ResourceManager.GetString("INSERT_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Rules (RuleId, TopicId, Position, Comment, Active) 
        ///VALUES (@RuleId, @TopicId, @Position, @Comment, @Active).
        /// </summary>
        internal static string INSERT_RULES {
            get {
                return ResourceManager.GetString("INSERT_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Topics (TopicId, ParentTopicId, Position, Title, Expanded) 
        ///VALUES (@TopicId, @ParentTopicId, @Position, @Title, @Expanded).
        /// </summary>
        internal static string INSERT_TOPICS {
            get {
                return ResourceManager.GetString("INSERT_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Grammar.
        /// </summary>
        internal static string META_GRAMMAR {
            get {
                return ResourceManager.GetString("META_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {32C03E86-53DF-4765-9D96-6C5653311E99}.
        /// </summary>
        internal static string PASSWORD_GRAMMAR {
            get {
                return ResourceManager.GetString("PASSWORD_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkExamples.
        /// </summary>
        internal static string PK_EXAMPLES {
            get {
                return ResourceManager.GetString("PK_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string PK_GRAMMAR {
            get {
                return ResourceManager.GetString("PK_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkRules.
        /// </summary>
        internal static string PK_RULES {
            get {
                return ResourceManager.GetString("PK_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkTopics.
        /// </summary>
        internal static string PK_TOPICS {
            get {
                return ResourceManager.GetString("PK_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Grammar.Resources.Schema.Grammar.sql.
        /// </summary>
        internal static string SCHEMA_GRAMMAR {
            get {
                return ResourceManager.GetString("SCHEMA_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ExampleId, RuleId, Position, TargetText, NativeText, Active, Exception
        ///FROM Examples
        ///ORDER BY RuleId, Position.
        /// </summary>
        internal static string SELECT_EXAMPLES {
            get {
                return ResourceManager.GetString("SELECT_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT GrammarId, Title, Comment, TargetLang, NativeLang, Shuffle, ShowRule 
        ///FROM Grammar.
        /// </summary>
        internal static string SELECT_GRAMMAR {
            get {
                return ResourceManager.GetString("SELECT_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT RuleId, TopicId, Position, Comment, Active
        ///FROM Rules
        ///ORDER BY TopicId, Position.
        /// </summary>
        internal static string SELECT_RULES {
            get {
                return ResourceManager.GetString("SELECT_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TopicId, ParentTopicId, Position, Title, Expanded
        ///FROM Topics ORDER BY ParentTopicId, Position.
        /// </summary>
        internal static string SELECT_TOPICS {
            get {
                return ResourceManager.GetString("SELECT_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string TABLE_EXAMPLES {
            get {
                return ResourceManager.GetString("TABLE_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string TABLE_GRAMMAR {
            get {
                return ResourceManager.GetString("TABLE_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string TABLE_RULES {
            get {
                return ResourceManager.GetString("TABLE_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        internal static string TABLE_TOPICS {
            get {
                return ResourceManager.GetString("TABLE_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Examples 
        ///SET RuleId = @RuleId, Position = @Position, TargetText = @TargetText, NativeText = @NativeText, Active = @Active, Exception = @Exception
        ///WHERE ExampleId = @ExampleId.
        /// </summary>
        internal static string UPDATE_EXAMPLES {
            get {
                return ResourceManager.GetString("UPDATE_EXAMPLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Grammar 
        ///SET Title = @Title, Comment = @Comment, TargetLang = @TargetLang, NativeLang = @NativeLang, Shuffle = @Shuffle, ShowRule = @ShowRule
        ///WHERE GrammarId = @GrammarId.
        /// </summary>
        internal static string UPDATE_GRAMMAR {
            get {
                return ResourceManager.GetString("UPDATE_GRAMMAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Rules
        ///SET TopicId = @TopicId, Position = @Position, Comment = @Comment, Active = @Active
        ///WHERE RuleId = @RuleId.
        /// </summary>
        internal static string UPDATE_RULES {
            get {
                return ResourceManager.GetString("UPDATE_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Topics 
        ///SET ParentTopicId = @ParentTopicId, Position = @Position, Title = @Title, Expanded = @Expanded 
        ///WHERE TopicId = @TopicId.
        /// </summary>
        internal static string UPDATE_TOPICS {
            get {
                return ResourceManager.GetString("UPDATE_TOPICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.0.
        /// </summary>
        internal static string VERSION_FULL {
            get {
                return ResourceManager.GetString("VERSION_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        internal static string VERSION_SHORT {
            get {
                return ResourceManager.GetString("VERSION_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace Grammar 3.0.
        /// </summary>
        internal static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
