//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaSpace.Grammar.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LinguaSpace")]
        public string COMPANY {
            get {
                return ((string)(this["COMPANY"]));
            }
            set {
                this["COMPANY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Grammar")]
        public string PRODUCT {
            get {
                return ((string)(this["PRODUCT"]));
            }
            set {
                this["PRODUCT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0.0")]
        public string VERSION {
            get {
                return ((string)(this["VERSION"]));
            }
            set {
                this["VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WINDOWPLACEMENT {
            get {
                return ((string)(this["WINDOWPLACEMENT"]));
            }
            set {
                this["WINDOWPLACEMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement GrammarWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["GrammarWindowPlacement"]));
            }
            set {
                this["GrammarWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement ExampleWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["ExampleWindowPlacement"]));
            }
            set {
                this["ExampleWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement MainWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["MainWindowPlacement"]));
            }
            set {
                this["MainWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement PracticeWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["PracticeWindowPlacement"]));
            }
            set {
                this["PracticeWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement RuleWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["RuleWindowPlacement"]));
            }
            set {
                this["RuleWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LinguaSpace.Common.UI.WindowPlacement TopicWindowPlacement {
            get {
                return ((global::LinguaSpace.Common.UI.WindowPlacement)(this["TopicWindowPlacement"]));
            }
            set {
                this["TopicWindowPlacement"] = value;
            }
        }
    }
}
