//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaSpace.Words.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinguaSpace.Words.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionId.
        /// </summary>
        internal static string ACTION_ID {
            get {
                return ResourceManager.GetString("ACTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string ACTION_ID_MOD {
            get {
                return ResourceManager.GetString("ACTION_ID_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string ACTION_ID_PROMPT {
            get {
                return ResourceManager.GetString("ACTION_ID_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string ACTION_ID_RIGHT {
            get {
                return ResourceManager.GetString("ACTION_ID_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string ACTION_ID_WRONG {
            get {
                return ResourceManager.GetString("ACTION_ID_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification.
        /// </summary>
        internal static string ACTION_MOD {
            get {
                return ResourceManager.GetString("ACTION_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer.
        /// </summary>
        internal static string ACTION_PROMPT {
            get {
                return ResourceManager.GetString("ACTION_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Answer.
        /// </summary>
        internal static string ACTION_RIGHT {
            get {
                return ResourceManager.GetString("ACTION_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Answer.
        /// </summary>
        internal static string ACTION_WRONG {
            get {
                return ResourceManager.GetString("ACTION_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string ANSWER {
            get {
                return ResourceManager.GetString("ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnswerDate.
        /// </summary>
        internal static string ANSWER_DATE {
            get {
                return ResourceManager.GetString("ANSWER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antonyms.
        /// </summary>
        internal static string ANTONYMS {
            get {
                return ResourceManager.GetString("ANTONYMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep.
        /// </summary>
        internal static string BEEP {
            get {
                return ResourceManager.GetString("BEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CATEGORIES {
            get {
                return ResourceManager.GetString("CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId.
        /// </summary>
        internal static string CATEGORY_ID {
            get {
                return ResourceManager.GetString("CATEGORY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultVocabularyPath.
        /// </summary>
        internal static string DEFAULT_VOCABULARY_PATH {
            get {
                return ResourceManager.GetString("DEFAULT_VOCABULARY_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        internal static string DEFINITION {
            get {
                return ResourceManager.GetString("DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string EXAMPLE {
            get {
                return ResourceManager.GetString("EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkAntonymsMeanings.
        /// </summary>
        internal static string FK_ANTONYMS_MEANINGS {
            get {
                return ResourceManager.GetString("FK_ANTONYMS_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkAntonymsWords.
        /// </summary>
        internal static string FK_ANTONYMS_WORDS {
            get {
                return ResourceManager.GetString("FK_ANTONYMS_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkCategoriesMeanings.
        /// </summary>
        internal static string FK_CATEGORIES_MEANINGS {
            get {
                return ResourceManager.GetString("FK_CATEGORIES_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkHistoryActions.
        /// </summary>
        internal static string FK_HISTORY_ACTIONS {
            get {
                return ResourceManager.GetString("FK_HISTORY_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkHistoryMeanings.
        /// </summary>
        internal static string FK_HISTORY_MEANINGS {
            get {
                return ResourceManager.GetString("FK_HISTORY_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkHistoryVocabularies.
        /// </summary>
        internal static string FK_HISTORY_VOCABULARIES {
            get {
                return ResourceManager.GetString("FK_HISTORY_VOCABULARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkMeaningsCategories.
        /// </summary>
        internal static string FK_MEANINGS_CATEGORIES {
            get {
                return ResourceManager.GetString("FK_MEANINGS_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkMeaningsWords.
        /// </summary>
        internal static string FK_MEANINGS_WORDS {
            get {
                return ResourceManager.GetString("FK_MEANINGS_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkRelationsMeanings.
        /// </summary>
        internal static string FK_RELATIONS_MEANINGS {
            get {
                return ResourceManager.GetString("FK_RELATIONS_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkRelationsWords.
        /// </summary>
        internal static string FK_RELATIONS_WORDS {
            get {
                return ResourceManager.GetString("FK_RELATIONS_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkSynonymsMeanings.
        /// </summary>
        internal static string FK_SYNONYMS_MEANINGS {
            get {
                return ResourceManager.GetString("FK_SYNONYMS_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkSynonymsWords.
        /// </summary>
        internal static string FK_SYNONYMS_WORDS {
            get {
                return ResourceManager.GetString("FK_SYNONYMS_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkTranslationsMeanings.
        /// </summary>
        internal static string FK_TRANSLATIONS_MEANINGS {
            get {
                return ResourceManager.GetString("FK_TRANSLATIONS_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FkWordsTypes.
        /// </summary>
        internal static string FK_WORDS_TYPES {
            get {
                return ResourceManager.GetString("FK_WORDS_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoryId.
        /// </summary>
        internal static string HISTORY_ID {
            get {
                return ResourceManager.GetString("HISTORY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialWeight.
        /// </summary>
        internal static string INITIAL_WEIGHT {
            get {
                return ResourceManager.GetString("INITIAL_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeaningCategoryId.
        /// </summary>
        internal static string MEANING_CATEGORY_ID {
            get {
                return ResourceManager.GetString("MEANING_CATEGORY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeaningId.
        /// </summary>
        internal static string MEANING_ID {
            get {
                return ResourceManager.GetString("MEANING_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meanings.
        /// </summary>
        internal static string MEANINGS {
            get {
                return ResourceManager.GetString("MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeaningsCategories.
        /// </summary>
        internal static string MEANINGS_CATEGORIES {
            get {
                return ResourceManager.GetString("MEANINGS_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Words.Profile.
        /// </summary>
        internal static string META_PROFILE {
            get {
                return ResourceManager.GetString("META_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Words.Vocabulary.
        /// </summary>
        internal static string META_VOCABULARY {
            get {
                return ResourceManager.GetString("META_VOCABULARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string MODIFIED {
            get {
                return ResourceManager.GetString("MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NativeLang.
        /// </summary>
        internal static string NATIVE_LANG {
            get {
                return ResourceManager.GetString("NATIVE_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4AEA9869-B312-4177-BDBB-3088F0410C5D}.
        /// </summary>
        internal static string PASSWORD_PROFILE {
            get {
                return ResourceManager.GetString("PASSWORD_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {F87B1C75-0486-4cec-ACBC-7B158DD75B4B}.
        /// </summary>
        internal static string PASSWORD_VOCABULARY {
            get {
                return ResourceManager.GetString("PASSWORD_VOCABULARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&amp;business=sales%40linguaspace%2ecom&amp;item_name={0}&amp;item_number={1}&amp;amount=10%2e00&amp;no_shipping=2&amp;no_note=1&amp;currency_code=USD&amp;lc=US&amp;bn=PP%2dBuyNowBF&amp;charset=UTF%2d8.
        /// </summary>
        internal static string PAYPAL {
            get {
                return ResourceManager.GetString("PAYPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkActions.
        /// </summary>
        internal static string PK_ACTIONS {
            get {
                return ResourceManager.GetString("PK_ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkCategories.
        /// </summary>
        internal static string PK_CATEGORIES {
            get {
                return ResourceManager.GetString("PK_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkHistory.
        /// </summary>
        internal static string PK_HISTORY {
            get {
                return ResourceManager.GetString("PK_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkMeanings.
        /// </summary>
        internal static string PK_MEANINGS {
            get {
                return ResourceManager.GetString("PK_MEANINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkMeaningsCategories.
        /// </summary>
        internal static string PK_MEANINGS_CATEGORIES {
            get {
                return ResourceManager.GetString("PK_MEANINGS_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkProfiles.
        /// </summary>
        internal static string PK_PROFILES {
            get {
                return ResourceManager.GetString("PK_PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkRelations.
        /// </summary>
        internal static string PK_RELATIONS {
            get {
                return ResourceManager.GetString("PK_RELATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkTranslations.
        /// </summary>
        internal static string PK_TRANSLATIONS {
            get {
                return ResourceManager.GetString("PK_TRANSLATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkTypes.
        /// </summary>
        internal static string PK_TYPES {
            get {
                return ResourceManager.GetString("PK_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkVocabularies.
        /// </summary>
        internal static string PK_VOCABULARIES {
            get {
                return ResourceManager.GetString("PK_VOCABULARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PkWords.
        /// </summary>
        internal static string PK_WORDS {
            get {
                return ResourceManager.GetString("PK_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string POSITION {
            get {
                return ResourceManager.GetString("POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix.
        /// </summary>
        internal static string POSTFIX {
            get {
                return ResourceManager.GetString("POSTFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string PREFIX {
            get {
                return ResourceManager.GetString("PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfileId.
        /// </summary>
        internal static string PROFILE_ID {
            get {
                return ResourceManager.GetString("PROFILE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string PROFILES {
            get {
                return ResourceManager.GetString("PROFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromptWeight.
        /// </summary>
        internal static string PROMPT_WEIGHT {
            get {
                return ResourceManager.GetString("PROMPT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        internal static string RELATION {
            get {
                return ResourceManager.GetString("RELATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelationId.
        /// </summary>
        internal static string RELATION_ID {
            get {
                return ResourceManager.GetString("RELATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        internal static string RELATIONS {
            get {
                return ResourceManager.GetString("RELATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightWeight.
        /// </summary>
        internal static string RIGHT_WEIGHT {
            get {
                return ResourceManager.GetString("RIGHT_WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Words.Resources.Schema.Profile.sql.
        /// </summary>
        internal static string SCHEMA_PROFILE {
            get {
                return ResourceManager.GetString("SCHEMA_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.Words.Resources.Schema.Vocabulary.sql.
        /// </summary>
        internal static string SCHEMA_VOCABULARY {
            get {
                return ResourceManager.GetString("SCHEMA_VOCABULARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string SLEEP {
            get {
                return ResourceManager.GetString("SLEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncLive.
        /// </summary>
        internal static string SYNC_LIVE {
            get {
                return ResourceManager.GetString("SYNC_LIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncMod.
        /// </summary>
        internal static string SYNC_MOD {
            get {
                return ResourceManager.GetString("SYNC_MOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SynonymId.
        /// </summary>
        internal static string SYNONYM_ID {
            get {
                return ResourceManager.GetString("SYNONYM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        internal static string SYNONYMS {
            get {
                return ResourceManager.GetString("SYNONYMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TargetLang.
        /// </summary>
        internal static string TARGET_LANG {
            get {
                return ResourceManager.GetString("TARGET_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string TRANSLATION {
            get {
                return ResourceManager.GetString("TRANSLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranslationId.
        /// </summary>
        internal static string TRANSLATION_ID {
            get {
                return ResourceManager.GetString("TRANSLATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        internal static string TRANSLATIONS {
            get {
                return ResourceManager.GetString("TRANSLATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeId.
        /// </summary>
        internal static string TYPE_ID {
            get {
                return ResourceManager.GetString("TYPE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string TYPES {
            get {
                return ResourceManager.GetString("TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabularies.
        /// </summary>
        internal static string VOCABULARIES {
            get {
                return ResourceManager.GetString("VOCABULARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VocabularyId.
        /// </summary>
        internal static string VOCABULARY_ID {
            get {
                return ResourceManager.GetString("VOCABULARY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WORD {
            get {
                return ResourceManager.GetString("WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordId.
        /// </summary>
        internal static string WORD_ID {
            get {
                return ResourceManager.GetString("WORD_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string WORDS {
            get {
                return ResourceManager.GetString("WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongWeight.
        /// </summary>
        internal static string WRONG_WEIGHT {
            get {
                return ResourceManager.GetString("WRONG_WEIGHT", resourceCulture);
            }
        }
    }
}
