//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaSpace.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinguaSpace.Common.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string _VERSION {
            get {
                return ResourceManager.GetString("_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdapterRAM.
        /// </summary>
        public static string ADAPTERRAM {
            get {
                return ResourceManager.GetString("ADAPTERRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdapterType.
        /// </summary>
        public static string ADAPTERTYPE {
            get {
                return ResourceManager.GetString("ADAPTERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        public static string ARCHITECTURE {
            get {
                return ResourceManager.GetString("ARCHITECTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        public static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOS.
        /// </summary>
        public static string BIOS {
            get {
                return ResourceManager.GetString("BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildNumber.
        /// </summary>
        public static string BUILDNUMBER {
            get {
                return ResourceManager.GetString("BUILDNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildType.
        /// </summary>
        public static string BUILDTYPE {
            get {
                return ResourceManager.GetString("BUILDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        public static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string CAPTION {
            get {
                return ResourceManager.GetString("CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDROMDrive.
        /// </summary>
        public static string CDROMDRIVE {
            get {
                return ResourceManager.GetString("CDROMDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryCode.
        /// </summary>
        public static string COUNTRYCODE {
            get {
                return ResourceManager.GetString("COUNTRYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesktopMonitor.
        /// </summary>
        public static string DESKTOPMONITOR {
            get {
                return ResourceManager.GetString("DESKTOPMONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskDrive.
        /// </summary>
        public static string DISKDRIVE {
            get {
                return ResourceManager.GetString("DISKDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string FAMILY {
            get {
                return ResourceManager.GetString("FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x{0}.
        /// </summary>
        public static string FORMAT_HEX {
            get {
                return ResourceManager.GetString("FORMAT_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSID\{{{0}}}.
        /// </summary>
        public static string FORMAT_TRIAL_COUNTER_PATH {
            get {
                return ResourceManager.GetString("FORMAT_TRIAL_COUNTER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallDate.
        /// </summary>
        public static string INSTALLDATE {
            get {
                return ResourceManager.GetString("INSTALLDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterfaceType.
        /// </summary>
        public static string INTERFACETYPE {
            get {
                return ResourceManager.GetString("INTERFACETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsKeyCodeValid.
        /// </summary>
        public static string IS_KEY_CODE_VALID {
            get {
                return ResourceManager.GetString("IS_KEY_CODE_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyCode.
        /// </summary>
        public static string KEY_CODE {
            get {
                return ResourceManager.GetString("KEY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key code is not valid..
        /// </summary>
        public static string KEY_CODE_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("KEY_CODE_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key code is valid..
        /// </summary>
        public static string KEY_CODE_IS_VALID {
            get {
                return ResourceManager.GetString("KEY_CODE_IS_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LEVEL {
            get {
                return ResourceManager.GetString("LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACAddress.
        /// </summary>
        public static string MACADDRESS {
            get {
                return ResourceManager.GetString("MACADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string MAJOR_VERSION {
            get {
                return ResourceManager.GetString("MAJOR_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string MANUFACTURER {
            get {
                return ResourceManager.GetString("MANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string MINOR_VERSION {
            get {
                return ResourceManager.GetString("MINOR_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string MODEL {
            get {
                return ResourceManager.GetString("MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitorManufacturer.
        /// </summary>
        public static string MONITORMANUFACTURER {
            get {
                return ResourceManager.GetString("MONITORMANUFACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotherboardDevice.
        /// </summary>
        public static string MOTHERBOARDDEVICE {
            get {
                return ResourceManager.GetString("MOTHERBOARDDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string NAME1 {
            get {
                return ResourceManager.GetString("NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkAdapter.
        /// </summary>
        public static string NETWORKADAPTER {
            get {
                return ResourceManager.GetString("NETWORKADAPTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperatingSystem.
        /// </summary>
        public static string OPERATINGSYSTEM {
            get {
                return ResourceManager.GetString("OPERATINGSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string PATCH_VERSION {
            get {
                return ResourceManager.GetString("PATCH_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryBusType.
        /// </summary>
        public static string PRIMARYBUSTYPE {
            get {
                return ResourceManager.GetString("PRIMARYBUSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor.
        /// </summary>
        public static string PROCESSOR {
            get {
                return ResourceManager.GetString("PROCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessorId.
        /// </summary>
        public static string PROCESSORID {
            get {
                return ResourceManager.GetString("PROCESSORID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessorType.
        /// </summary>
        public static string PROCESSORTYPE {
            get {
                return ResourceManager.GetString("PROCESSORTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace Words 3.0.0.
        /// </summary>
        public static string PRODUCT_VERSION_FULL {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinguaSpace Words 3.0.
        /// </summary>
        public static string PRODUCT_VERSION_SHORT {
            get {
                return ResourceManager.GetString("PRODUCT_VERSION_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {DD6763D7-FC91-4811-A27B-431574D0CA8B}.
        /// </summary>
        public static string REG_FILE_SIGNITURE {
            get {
                return ResourceManager.GetString("REG_FILE_SIGNITURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisteredUser.
        /// </summary>
        public static string REGISTEREDUSER {
            get {
                return ResourceManager.GetString("REGISTEREDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryBusType.
        /// </summary>
        public static string SECONDARYBUSTYPE {
            get {
                return ResourceManager.GetString("SECONDARYBUSTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Meta.
        /// </summary>
        public static string SELECT_META {
            get {
                return ResourceManager.GetString("SELECT_META", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        public static string SERIALNUMBER {
            get {
                return ResourceManager.GetString("SERIALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        public static string SHA1 {
            get {
                return ResourceManager.GetString("SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMBIOSBIOSVersion.
        /// </summary>
        public static string SMBIOSBIOSVERSION {
            get {
                return ResourceManager.GetString("SMBIOSBIOSVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMBIOSMajorVersion.
        /// </summary>
        public static string SMBIOSMAJORVERSION {
            get {
                return ResourceManager.GetString("SMBIOSMAJORVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMBIOSMinorVersion.
        /// </summary>
        public static string SMBIOSMINORVERSION {
            get {
                return ResourceManager.GetString("SMBIOSMINORVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundDevice.
        /// </summary>
        public static string SOUNDDEVICE {
            get {
                return ResourceManager.GetString("SOUNDDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stepping.
        /// </summary>
        public static string STEPPING {
            get {
                return ResourceManager.GetString("STEPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.0.
        /// </summary>
        public static string VERSION_FULL {
            get {
                return ResourceManager.GetString("VERSION_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        public static string VERSION_SHORT {
            get {
                return ResourceManager.GetString("VERSION_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VideoController.
        /// </summary>
        public static string VIDEOCONTROLLER {
            get {
                return ResourceManager.GetString("VIDEOCONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32_.
        /// </summary>
        public static string WIN32_ {
            get {
                return ResourceManager.GetString("WIN32_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsDirectory.
        /// </summary>
        public static string WINDOWSDIRECTORY {
            get {
                return ResourceManager.GetString("WINDOWSDIRECTORY", resourceCulture);
            }
        }
    }
}
